blank_issues_enabled: true
contact_links:
  - name: VSH / Freak Fortress Forum
    url: https://forums.alliedmods.net/forumdisplay.php?f=154
    about: Issue specific to your server, bosses, or subplugins.
