name: Package

on:
  push:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.10" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/date.sh
      
      - name: Compile
        run: |
          mkdir -p build/addons/sourcemod/plugins/freaks
          cd build/addons/sourcemod/scripting
          ./spcomp -E freak_fortress_2.sp -o ../plugins/freak_fortress_2.smx
          ./spcomp -E freaks/ffbat_defaults.sp -o ../plugins/freaks/ffbat_defaults.ff2
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: FreakFortressBat-${{env.DATE_VERSION}}
          path: ./build/package